name: Check for the tutorial update

on:
  pull_request:
    paths:
      - "MobileRobotUITutorialProject/**"
      - "UnityScripts/**"

jobs:
  check-tutorial-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: File sync
        run: |
          ./.github/scripts/sync_scripts.sh
          git status | grep "working tree clean" && exit 0 || git status; exit 1;
